version: '3.9'
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./postgresql/postgres.env
    volumes:
      - pgdb_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./pgadmin/pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/.pgpass:/pgpass
    depends_on:
      - database

volumes:
  pgdb_data:
  pgadmin_data:
