/api/v1/member/{number}:
  get:
    summary: Get a member by number
    parameters:
      - in: path
        name: number
        schema:
          type: integer
        required: true
        description: Number of member to get
    tags:
      - Members
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    number:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "John Wick"
                    status:
                      type: boolean
                      example: true
                    phone_one:
                      type: string
                      example: "1234567890"
                    phone_two:
                      type: string
                      example: "9876543210"
                    address:
                      type: string
                      example: "Direccion 1"
                    district:
                      type: string
                      example: "Barrio 1"
                    payday:
                      type: integer
                      example: 10
                    last_pay_amount:
                      type: integer
                      example: 2500
                    plan_id:
                      type: integer
                      example: 1
                    created_at:
                      type: string
                      example: "2023-08-20T11:00:00"
                success: 
                  type: boolean
                  example: true
                message: 
                  type: string
                  example: "Successfully obtained members"
                error:
                  type: object
                  default: null

  delete:
    summary: Delete a member by number
    parameters:
      - in: path
        name: number
        schema:
          type: integer
        required: true
        description: Number of member to delete
    tags:
      - Members
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    number:
                      type: integer
                      example: 1
                success: 
                  type: boolean
                  example: true
                message: 
                  type: string
                  example: "Member delete successfully"
                error:
                  type: object
                  default: null

  put:
    summary: Update a member by number
    parameters:
      - in: path
        name: number
        schema:
          type: integer
        required: true
        description: Number of member to update
    tags:
      - Members
    requestBody:
      description: Optional description in *Markdown*
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              number:
                type: integer
                example: 1
              name:
                type: string
                example: "John Wick"
              status:
                type: boolean
                example: true
              phone_one:
                type: string
                example: "1234567890"
              phone_two:
                type: string
                example: "9876543210"
              address:
                type: string
                example: "Direccion 1"
              district:
                type: string
                example: "Barrio 1"
              payday:
                type: integer
                example: 10
              last_pay_amount:
                type: integer
                example: 2500
              plan_id:
                type: integer
                example: 1
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    number:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "John Wick"
                    status:
                      type: boolean
                      example: true
                    phone_one:
                      type: string
                      example: "1234567890"
                    phone_two:
                      type: string
                      example: "9876543210"
                    address:
                      type: string
                      example: "Direccion 1"
                    district:
                      type: string
                      example: "Barrio 1"
                    payday:
                      type: integer
                      example: 10
                    last_pay_amount:
                      type: integer
                      example: 2500
                    plan_id:
                      type: integer
                      example: 1
                    created_at:
                      type: string
                      example: "2023-08-20T11:00:00"
                success: 
                  type: boolean
                  example: true
                message: 
                  type: string
                  example: "Successfully obtained members"
                error:
                  type: object
                  default: null

/api/v1/member:
  post:
    summary: Create a member
    tags:
      - Members
    requestBody:
      description: Optional description in *Markdown*
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              number:
                type: integer
                example: 1
              name:
                type: string
                example: "John Wick"
              status:
                type: boolean
                example: true
              phone_one:
                type: string
                example: "1234567890"
              phone_two:
                type: string
                example: "9876543210"
              address:
                type: string
                example: "Direccion 1"
              district:
                type: string
                example: "Barrio 1"
              payday:
                type: integer
                example: 10
              last_pay_amount:
                type: integer
                example: 2500
              plan_id:
                type: integer
                example: 1
            required:
              - number
              - name 
              - status
              - phone_one
              - address
              - district
              - payday
              - last_pay_amount
              - plan_id
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    number:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "John Wick"
                    status:
                      type: boolean
                      example: true
                    phone_one:
                      type: string
                      example: "1234567890"
                    phone_two:
                      type: string
                      example: "9876543210"
                    address:
                      type: string
                      example: "Direccion 1"
                    district:
                      type: string
                      example: "Barrio 1"
                    payday:
                      type: integer
                      example: 10
                    last_pay_amount:
                      type: integer
                      example: 2500
                    plan_id:
                      type: integer
                      example: 1
                    created_at:
                      type: string
                      example: "2023-08-20T11:00:00"
                success: 
                  type: boolean
                  example: true
                message: 
                  type: string
                  example: "Member created successfully"
                error:
                  type: object
                  default: null
  
  get:
    summary: Get all member
    parameters:
      - in: query
        name: offset
        type: integer
        required: false
        default: 0
        minimum: 0
        description: The number of members to skip before starting to collect the result set
      - in: query
        name: limit
        type: integer
        required: false
        default: 20
        minimum: 1
        maximum: 100
        description: The numbers of members to return
    tags:
      - Members
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      number:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "John Wick"
                      status:
                        type: boolean
                        example: true
                      phone_one:
                        type: string
                        example: "1234567890"
                      phone_two:
                        type: string
                        example: "9876543210"
                      address:
                        type: string
                        example: "Direccion 1"
                      district:
                        type: string
                        example: "Barrio 1"
                      payday:
                        type: integer
                        example: 10
                      last_pay_amount:
                        type: integer
                        example: 2500
                      plan_id:
                        type: integer
                        example: 1
                      created_at:
                        type: string
                        example: "2023-08-20T11:00:00"
                  success: 
                    type: boolean
                    example: true
                  message: 
                    type: string
                    example: "Successfully obtained members"
                  error:
                    type: object
                    default: null
